@echo off
chcp 65001 >nul
title 🍽️ SmartMeal-Planner - Repas sains & intelligents
echo Lancement de SmartMeal-Planner...
echo.
echo 🎨 Design moderne chargé...
echo 🍽️  Générateur de repas premium...
echo 📊  Interface utilisateur avancée...
echo.
py main.py
pause